name: "Liquibase POC"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test-liquibase-action:
    runs-on: self-hosted
    name: Liquibase Status
    steps:
      - name: Liquibase status
        id: run-liquibase-history
        run:  |
          cd /home/wzhou/liquibase-test
          liquibase --username="postgres" --defaults-file="liquibase.properties" history
